### ISSUE TITLE
Can you remove the text of the song that is in the corner, please make it an adjustment 

### ISSUE THREAD

**Issue by AStupidPersonXd123** [MobilePorting/JS-Engine-Mobile#1]
### What is your question?

Pls

**Comment by mcagabe19** [comment]
open issue to upstream not here

**Comment by JordanSantiagoYT** [comment]
> ### What is your question?
> Pls

1. move the issue to https://github.com/JordanSantiagoYT/FNF-PsychEngine-NoBotplayLag/issues
2. ..that's a watermark that you can disable
