### ISSUE TITLE
volted jsons don't work well 

### ISSUE THREAD

**Issue by AStupidPersonXd123** [MobilePorting/JS-Engine-Mobile#2]
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

When I play a mod with a character with the configuration of voltiar character the json of the movements do not work well 

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mcagabe19** [comment]
upstream issue, please open issue to upstream

**Comment by JordanSantiagoYT** [comment]
possibly your voltiar json is a playable character formatted json, in that case you'll have to resave the json in the character editor with "Playable Character" checked
